apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgCYvJHh69q7blLd56wW2IGqh32XhhyPHrXRGwMf5RdZShIE3K3bC3H9+4L/Z4yPREV/fpBeSxmPP+QEas4J/iiy5MpQlRacz9PW/sshUedJF7jzaAb4UjmnUPHy3MaOlFN4OmRFXZZFkObZzF/bdW9Nc8hwyHOk92++V0qUaCp6C3uad/Sh+K0wOlqRfrAKQ/PBGM9VMG1zD2ch3h5uR23C466pi51tmARrRt3BmDxWuXj0Fh96HN8khVWM1p+wVgWvUYygEpQ+uAHw+tddKRhK6HEtKIGmuZwOnHcyVkd+hWmySmDLPQsc9NXmgQ9WiaseO5l+qR8WFLwQ6xCqa/1Ojno2hR0c3UzQW4pGNAUX3dnO4y/EigwHOy4R/j6li6kZACEKh5oIxV6d0Ag3uuR4EoSFZvT/ETtNkO6TkNLyi8+BdcnIsR0FRoAXCo7GbW/fypm8FH30QQpIw22WGh6jFqWUU1Kg9Fm3tXAoL+wwjcJbo5OuteUqeEM+529SKZt+tI9sA3N3QgAsUgecshLYeCdKk0YIlBFgr8mCdpM6/gwLcVmfu9/J3TYFr+fE6kuqvDcVcAQGgl9b2EyQCcbRPe18kihYkbmA5aJ7ytNDCUPGFZrWQeHkCsV3GKZ+eurnfNXiVxzfhUmK/vaH43G0c+8cEXGVBnewb0fJ0zNaYvaGk/X5WSqz/bEyuE4Mr0Ok2U1d66HvLWXRqLHNpSzV1ARrDYipEeroQtmjFzeKN/eXSqxMGPA=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default

