apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
spec:
  project: default
  source:
    repoURL: 'https://github.com/anilho/samplegitopsapp.git'
    path: argo-cd
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
