apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: caddy
    namespace: argocd
spec:
    project: default
    source:
      repoURL: 'https://github.com/anilho/samplegitopsapp.git'
      path: overlays
      targetRevision: master
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: default
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
